import { OlympicsProvider } from "./data/context/OlympicsContext"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <OlympicsProvider>
        <body>{children}</body>
      </OlympicsProvider>
    </html>
  )
}
